### PR TITLE
Add macros for testing: check_memory, check_memory_address and  not_continuous_references macros for testing

### PR DESCRIPTION
**Pull request by pefontana**
# Add macros for testing: check_memory, check_memory_address and  not_continuous_references macros for testing

## Description

Add the following macros to avoid boilerplate code in testing:
* check_memory: Asserts memory addresses and values
* check_memory_address: Asserts memory address and value
* not_continuous_references: Create hint references with no continuous offset

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Comment by entropidelic** [comment]
Looks good! Just add a simple test for the macros, like the memory macro has. If something underneath changes, it will be much easier to know if the macro brakes, they tend to be cumbersome to debug

**Comment by pefontana** [comment]
> Yes, @entropidelic you are right
I  made some unit test [here](https://github.com/lambdaclass/cleopatra_cairo/pull/356/commits/7241623aed27da884d2203882c04c66cc3291a25)

**Review by entropidelic — APPROVED** [review]

**Comment by entropidelic** [comment]
LGTM!

**Review by fmoletta — APPROVED** [review]
Great Work!

**Review by Juan-M-V — APPROVED** [review]
LG(reat)TM

**Pull request merged**
